### PR TITLE
1.0

### PR DESCRIPTION
**Pull request by lindyhopchris**
So this is a work in progress pull request for what 1.0 could potentially look like. Opening this for discussion!

Thing's I've added:

- Sweet alert now imported via npm not bower
- Positional params for the component
- All sweet alert configuration options supported by the component
- Component sweet alert promise is run loop aware (wrapped it in an RSVP promise)
- Configuration can be set using the `ember-sweetalert` key
- Initial integration tests

Some example usages:

```hbs
{{sweet-alert "Ember CLI Sweet Alert" "Awesome!" "success"
  show=toggleModal
  onOpen=(action (mut cancellation) null)
  onConfirm=(action (mut enterEmail) true)
  onCancel=(action "cancelled")
}}

{{sweet-alert
  show=enterEmail
  title="Submit email to run ajax request"
  input="email"
  showCancelButton=true
  confirmButtonText="submit"
  allowOutsideClick=false
  preConfirm=(action "loading")
  onConfirm=(action "updateEmail")
}}
```

Things to add:

- All the sweet alert callback options (e.g. `onOpen`, `onClose`) need to be bound to the run loop.
- Would be useful for this addon to provide test helpers.

Let me know comments and ideas!

### CODE REVIEW

**Comment by Tonkpils** [comment]
These changes all look good to me so far. I'm really excited to provide this through `npm` and not bower.

> Would be useful for this addon to provide test helpers.

I definitely think this would be really useful for users.

@lindyhopchris I really appreciate you taking lead on this upgrade and moving the addon forward. 🙇

**Comment by lindyhopchris** [comment]
@Tonkpils no problem. sorry it's taken me so long to get round to it - had to wait until it was something I actually needed to do as part of what I'm working on. 

Will push some more commits with some of the extra stuff.

**Comment by al3x-edge** [comment]
@lindyhopchris Apologies if this is too soon; been waiting on this one for a bit and in the same position as you. Tried to install this into a project, but it's failing on calling sweetAlert it seems on this line `(0, _sweetalert.default)(props).then(resolve, reject);`.

Is this something we can work on clearing up? May just be that I'm not import properly.

```
VM3151:1 Uncaught TypeError: _sweetalert.default is not a function
    at eval (eval at <anonymous> (vendor.js:132937), <anonymous>:1:20)
    at vendor.js:132937
    at initializePromise (vendor.js:66127)
    at new Promise (vendor.js:66607)
    at Class._displaySweetAlert (vendor.js:132936)
    at Class.didInsertElement (vendor.js:132924)
    at Class.superWrapper [as didInsertElement] (vendor.js:58716)
    at Class.trigger (vendor.js:61003)
    at Class.superWrapper [as trigger] (vendor.js:58716)
    at CurlyComponentManager.didCreate (vendor.js:34678)
```
```
new Ember.RSVP.Promise(function (resolve, reject) {
          (0, _sweetalert.default)(props).then(resolve, reject);
        }).then(result => {
          if (result.value) {
            Ember.get(this, 'onConfirm')(result);
          } else {
            Ember.get(this, 'onCancel')(result);
          }

          Ember.set(this, 'show', false);
        });
```

**Comment by lindyhopchris** [comment]
Hi @al3x-edge 

I just installed the 1.0 branch in a fresh Ember app and the `{{sweet-alert}}` component is working fine. So not sure what's going on in your app. In upgrading did you remove sweet alert from your `bower.json`?

**Comment by al3x-edge** [comment]
Might not have actually. I’ll give it a shot when I get a chance later
today. Is there a specific way to install to a new project besides ember
install <embersa-url>#1.0?

**Comment by al3x-edge** [comment]
@lindyhopchris  SweetAlert was still in the bower.json so I removed it from there.  After I cleared out the tmp folders, I'm still getting the same error when the `{{sweet-alert}}` component is triggered with `true` from the `show` computed property.

Template snippet
```
{{sweet-alert
  show=temperatureTooHigh
  title="Temperature Too High"
  text="The temperature entered exceeds the maximum temperature limit."
  icon="error"
  confirmButtonText="Try again"
}}
```

```
  temperatureTooHigh: computed('pumpApplication.temperature', function() {
    return this.get('pumpApplication.temperature') > 300;
  }),
```

ember -v
```
ember-cli: 3.2.0
node: 6.14.1
os: darwin x64
```

package.json
```
{
  "name": "tester",
  "version": "0.0.0",
  "description": "",
  "license": "All Rights Reserved",
  "author": "fh group",
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "repository": "",
  "scripts": {
    "build": "ember build",
    "lint:js": "eslint .",
    "start": "ember serve",
    "test": "ember test"
  },
  "devDependencies": {
    "broccoli-asset-rev": "^2.7.0",
    "ember-ajax": "^3.0.0",
    "ember-cli": "~3.2.0",
    "ember-cli-app-version": "^3.0.0",
    "ember-cli-babel": "^6.6.0",
    "ember-cli-bootstrap-sassy": "^0.5.8",
    "ember-cli-dependency-checker": "^2.0.0",
    "ember-cli-eslint": "^4.2.1",
    "ember-cli-htmlbars": "^2.0.1",
    "ember-cli-htmlbars-inline-precompile": "^1.0.0",
    "ember-cli-inject-live-reload": "^1.4.1",
    "ember-cli-moment-shim": "^3.5.0",
    "ember-cli-nouislider": "^0.14.1",
    "ember-cli-qunit": "^4.3.2",
    "ember-cli-sass": "^7.2.0",
    "ember-cli-shims": "^1.2.0",
    "ember-cli-sri": "^2.1.0",
    "ember-cli-uglify": "^2.0.0",
    "ember-cli-update": "^0.21.4",
    "ember-concurrency": "^0.8.16",
    "ember-cpm": "^3.0.0",
    "ember-d3": "^0.4.4",
    "ember-data": "~3.2.0",
    "ember-export-application-global": "^2.0.0",
    "ember-feature-flags": "^4.2.0",
    "ember-file-upload": "^2.5.0",
    "ember-font-awesome": "^3.1.1",
    "ember-get-config": "^0.2.4",
    "ember-inflector": "2.1.0",
    "ember-inputmask": "^0.6.0",
    "ember-load-initializers": "^1.1.0",
    "ember-local-storage": "^1.3.6",
    "ember-lodash": "~4.17.6",
    "ember-maybe-import-regenerator": "^0.1.6",
    "ember-modal-dialog": "^2.4.1",
    "ember-moment": "^7.6.0",
    "ember-page-title": "^4.0.3",
    "ember-parachute": "^0.3.7",
    "ember-resolver": "^4.0.0",
    "ember-select": "0.4.0",
    "ember-simple-auth": "^1.6.0",
    "ember-source": "~3.2.0",
    "ember-sweetalert": "https://github.com/Tonkpils/ember-sweetalert.git#1.0",
    "ember-tri-state": "^1.0.1",
    "ember-truth-helpers": "^2.0.0",
    "ember-watson": "^0.9.1",
    "ember-welcome-page": "^3.0.0",
    "ember-wormhole": "^0.5.4",
    "eslint-plugin-ember": "^5.0.0",
    "loader.js": "^4.2.3",
    "qunit-dom": "^0.6.2"
  },
  "private": true,
  "dependencies": {
    "accounting": "^0.4.1",
    "d3": "^5.3.0",
    "ember-concurrency": "^0.8.16",
    "spinkit": "^1.2.5"
  },
  "engines": {
    "node": "6.* || 8.* || >= 10.*"
  }
}
```
bower.json
```
{
  "name": "tester",
  "dependencies": {
    "canvas": "http://cdnjs.cloudflare.com/ajax/libs/canvasjs/1.4.1/canvas.min.js",
    "jquery.inputmask": "3.1.49",
    "js-quantities": "~1.5.0",
    "print-area": "~2.4.1",
    "ravenjs": "http://cdn.ravenjs.com/3.12.1/raven.min.js",
    "round": "https://gist.githubusercontent.com/al3x-edge/01c8b37ce44476ba8aaa/raw/eb3020675f163f7def10939f71d7f4b94d75b3e1/round.js"
  }
}
```

**Comment by lindyhopchris** [comment]
@Tonkpils think this can probably be merged into `develop` now? Also, maybe we should release a `1.0.0-alpha.1`? Would definitely be good to get feedback from people before actually releasing as `1.0.0`.

**Comment by lindyhopchris** [comment]
@Tonkpils I'm back on something at work that has Ember Sweet Alert in it, so this is my opportunity to try to get this all sorted. Should I proceed with merging and sorting out the remaining issues? Also did you want to give me access for doing NPM releases? You did offer at one stage and guessing from your silence that it might be a good idea if you don't have time to look at this project?

**Comment by Tonkpils** [comment]
Hey! Sorry it took me long to get back to you. Yeah, I can definitely give you access! Let me get to a computer and I’ll do that right away :)

**Comment by lindyhopchris** [comment]
@Tonkpils just emailed you!

**Pull request merged**
