### PR TITLE
Updated To Sweetalert2 version 7.19.0

### PR DESCRIPTION
**Pull request by Shaneprrlt**

### CODE REVIEW

**Comment by Tonkpils** [comment]
Thanks for taking the time to submit this PR @Shaneprrlt 

This all looks good to me. @lindyhopchris would you be able to test this to make sure it works correctly?

Since this is part of https://github.com/Tonkpils/ember-sweetalert/issues/10 I think it'd get us a step closer to that 😄

**Comment by lindyhopchris** [comment]
I get errors with an `npm install`, which is something to do with this commit adding a `package-lock.json`. If I delete the lock file and re-run `npm install` it runs fine. I suggest we don't add the package-lock on this PR?

The other thing is the `ember test` fails on this PR but doesn't on `master`. I think this might be related to us needing to update to a newer version of Ember. I'll see if I can do that quickly now and push it to a new branch.

One other thing about this PR - it would need to be released as `0.2.0` rather than `0.1.2` because changing to a different major version of sweetalert could break consuming applications.

**Comment by Tonkpils** [comment]
That sounds good to me, @Shaneprrlt could you remove the addition of `package-lock` and remove the change to the version bump on `package.json` as we would take care of bumping the version once a new release is ready to go out. 

Once that's done, I'll point this to `develop` so we can merge that there

**Comment by Shaneprrlt** [comment]
@Tonkpils Yep, I'll get that fix pushed.

**Comment by Shaneprrlt** [comment]
@Tonkpils Apologies for the delay, just pushed those changes though.

**Pull request merged**
